package policy

import (
	"fmt"
	"strings"

	"github.com/MemorManeo/whyopen/internal/facts"
	"github.com/MemorManeo/whyopen/internal/model"
)

// Init seeds a policy from a verdict set: the allow list is the host's
// current reachable ports, collapsed across families, and nothing else.
// Ports whyopen could not resolve come back separately rather than in the
// allow list, because writing them there would record "allow whatever I
// could not verify" in the file that decides whether later runs pass.
func Init(vs []model.Verdict) (Policy, []Entry) {
	p := Policy{FailOnUnknown: true}
	inAllow, inUnknown := map[Entry]bool{}, map[Entry]bool{}
	var unknown []Entry

	for _, v := range vs {
		e := Entry{Port: v.Endpoint.Port, Proto: v.Endpoint.Proto}
		switch v.Result {
		case "reachable":
			if !inAllow[e] {
				inAllow[e] = true
				p.Allow = append(p.Allow, e)
			}
		case "unknown":
			if !inUnknown[e] {
				inUnknown[e] = true
				unknown = append(unknown, e)
			}
		}
	}
	sortEntries(p.Allow)
	sortEntries(unknown)
	return p, unknown
}

// Marshal renders a policy as the file a human then edits. It is written
// by hand rather than through the YAML encoder because the comments are
// most of the value: a generated allow list nobody understands is one
// nobody maintains.
//
// unreadable is what the run could not turn into a port at all, today a
// destination rewrite forwarding ports whyopen cannot name
// (docs/decisions/0014-forwarded-ports-as-endpoints.md). It is written
// into the file as a comment for the same reason the unresolved ports
// are: this file is generated at the moment someone is deciding what
// their host may expose, and that is the moment to say what whyopen could
// not account for.
func Marshal(p Policy, unknown []Entry, unreadable []facts.Warning) []byte {
	var b strings.Builder
	b.WriteString("# whyopen policy, generated by `whyopen policy init`.\n")
	b.WriteString("# Every port reachable from the internet and not listed below is a\n")
	b.WriteString("# violation, and `whyopen check --policy` exits 1 on one. A listed port\n")
	b.WriteString("# that is not reachable is reported, but does not fail the run.\n")
	fmt.Fprintf(&b, "version: %d\n", Version)
	fmt.Fprintf(&b, "zones:\n  %s:\n    allow:", zoneName)
	if len(p.Allow) == 0 {
		b.WriteString(" []\n")
	} else {
		b.WriteString("\n")
		for _, e := range p.Allow {
			fmt.Fprintf(&b, "      - %s\n", e)
		}
	}
	if len(unknown) > 0 {
		b.WriteString("\n# whyopen could not resolve these ports when this file was written:\n")
		for _, e := range unknown {
			fmt.Fprintf(&b, "#   %s\n", e)
		}
		b.WriteString("# They are deliberately not allowed above: whyopen does not know whether\n")
		b.WriteString("# they are open, and an allow list is for ports you decided to open.\n")
	}
	if len(unreadable) > 0 {
		b.WriteString("\n# whyopen also found rewrites whose forwarded ports it could not name:\n")
		for _, w := range unreadable {
			for _, line := range wrapComment(w.Message) {
				fmt.Fprintf(&b, "#   %s\n", line)
			}
		}
		b.WriteString("# No entry above covers those, and none can: they name no port. They\n")
		b.WriteString("# are exposure this file cannot describe, which is what the setting\n")
		b.WriteString("# below is for.\n")
	}
	b.WriteString("\n# With this set, check exits 2 while any port is unresolved. Turning it\n")
	b.WriteString("# off makes the run green without making the host any more understood.\n")
	fmt.Fprintf(&b, "fail_on_unknown: %t\n", p.FailOnUnknown)
	return []byte(b.String())
}

// commentWidth keeps a wrapped comment inside the width the rest of this
// file is written to, so a generated policy still reads as one document
// rather than as a paragraph pasted into it.
const commentWidth = 70

// wrapComment breaks a warning into comment-sized lines on word
// boundaries. A word longer than the width is left long rather than cut:
// the words in these messages are rule locations and addresses, and a
// broken one is worse than a wide line.
func wrapComment(msg string) []string {
	var lines []string
	line := ""
	for _, word := range strings.Fields(msg) {
		switch {
		case line == "":
			line = word
		case len(line)+1+len(word) <= commentWidth:
			line += " " + word
		default:
			lines = append(lines, line)
			line = word
		}
	}
	if line != "" {
		lines = append(lines, line)
	}
	return lines
}
